[package]
name = "frostbite-gui"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Frostbite desktop GUI"

[[bin]]
name = "frostbite-gui"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
frostbite-core = { path = "../core" }
serde.workspace = true
serde_json.workspace = true
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "sync", "io-util"] }
tauri = { version = "2", features = ["devtools"] }
tauri-plugin-shell = "2"
tauri-plugin-localhost = "2"
portpicker = "0.1"
