#!/usr/bin/env bash
# Build the GrepFocus AppImage inside an ubuntu:22.04 podman container so the
# bundle links an old-enough glibc/webkit to run broadly. Run as your normal
# user (NOT root); needs podman. Outputs dist/GrepFocus-<ver>-x86_64.AppImage
# plus a stable-name dist/grepfocus.AppImage.
#
# Usage: ./packaging/build-appimage.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

IMAGE=grepfocus-appimage-builder

echo "==> Building the toolchain image ($IMAGE) [cached after the first run]"
podman build -t "$IMAGE" packaging/appimage

mkdir -p dist

echo "==> Building the AppImage in the container"
# Mirrors build-deb.sh's volume strategy: the repo is mounted at /src; named
# volumes cache the cargo registry and hold target/ + node_modules across runs,
# and target/ is mounted OVER /src/target so the container never mixes object
# files with a host (Fedora) build. dist/ is the host bind mount, so the finished
# AppImage copied there lands on the host.
#
# APPIMAGE_EXTRACT_AND_RUN=1: linuxdeploy/appimagetool need FUSE, which an
# unprivileged container lacks — this makes them self-extract instead.
podman run --rm \
    -e CI=true \
    -e APPIMAGE_EXTRACT_AND_RUN=1 \
    -v "$REPO_ROOT":/src:Z \
    -v grepfocus-appimage-cargo:/root/.cargo/registry \
    -v grepfocus-appimage-target:/src/target \
    -v /src/target/release/bundle \
    -v grepfocus-appimage-node:/src/crates/gui/ui/node_modules \
    "$IMAGE" bash -euo pipefail -c '
        # tauri-build regenerates crates/gui/gen + permissions/autogenerated on
        # every build; a stale copy on the mounted repo (e.g. from a host-side
        # cargo run) makes it panic "tauri-build failed: File exists". Clean them.
        rm -rf crates/gui/gen crates/gui/permissions/autogenerated

        # Build the UI explicitly (embedded into the GUI via frontendDist). The
        # overlay config neutralizes tauri.conf.json beforeBuildCommand so tauri
        # does not re-run it — its cwd for that hook differs across tauri-cli
        # versions (`--dir ui` doubled to ui/ui in-container), so we own the step.
        pnpm --dir crates/gui/ui install --frozen-lockfile
        pnpm --dir crates/gui/ui build
        # Force the GUI crate to recompile so generate_context! re-embeds the
        # fresh ui/dist — cargo does not reliably notice frontend-only changes
        # (same trap upgrade.sh documents), and a cached target volume would
        # otherwise ship a stale frontend inside a "new" AppImage.
        touch crates/gui/src/main.rs

        # Build the whole workspace release first so grepfocusd exists for the
        # bundle payload (staged by stage-payload.sh), then bundle the GUI as an
        # AppImage.
        cargo build --release --locked
        packaging/appimage/stage-payload.sh

        # NB: target/release/bundle is a fresh ANONYMOUS volume each run (see the
        # `-v /src/target/release/bundle` above), not part of the cached target
        # volume. linuxdeploy-plugin-gtk copies read-only system dirs (glib
        # schemas, gtk-3.0 / gdk-pixbuf modules) into the AppDir that, under
        # rootless podman, even container-root cannot later remove — so a
        # persisted bundle dir would poison the next build. Keeping it ephemeral
        # sidesteps that: every build starts with an empty bundle dir and never
        # has to delete those dirs.

        # --config merges bundle.resources (the daemon payload) + the neutralized
        # beforeBuildCommand in for this build only; the committed tauri.conf.json
        # omits both so plain cargo builds (rpm/deb/AUR/dev) are untouched.
        ( cd crates/gui && cargo tauri build --bundles appimage \
              --config ../../packaging/appimage/tauri.appimage.json )

        # Drop ALL bundled libwayland-*.so* and repack. Root cause (proven by
        # symbol audit + coredumps): the host GPU driver stack must resolve
        # libwayland at the HOST version — the AppDir copy (Ubuntu 22.04,
        # wayland 1.20) shadows it via LD_LIBRARY_PATH, and e.g. Fedora Mesa
        # references wl_fixes_interface (wayland 1.23), so dlopen of the Mesa
        # vendor lib fails -> glvnd has NO EGL vendors -> every platform (even
        # the web process surfaceless one) returns EGL_BAD_PARAMETER ->
        # WebKitWebProcess g_errors/SIGABRTs and the window stays white.
        # Any host new enough for our glibc floor ships libwayland >= 1.20
        # (GTK3 depends on it), so relying on the host copy is safe.
        # (WebKit still needs WEBKIT_EXEC_PATH to find its helper processes;
        # that is set in the GUI at startup under $APPIMAGE.)
        appdir=/src/target/release/bundle/appimage/GrepFocus.AppDir
        built=$(ls -1 /src/target/release/bundle/appimage/*.AppImage | head -n1)
        if ls "$appdir"/usr/lib/libwayland-*.so* >/dev/null 2>&1; then
            rm -f "$appdir"/usr/lib/libwayland-*.so*
            rm -f "$built"
            ARCH=x86_64 appimagetool "$appdir" "$built"
            echo "repacked without bundled libwayland libraries"
        fi

        # Copy via temp + rename: a plain cp onto a currently-RUNNING AppImage
        # fails with ETXTBSY, but rename atomically replaces the directory entry
        # while any running instance keeps its old inode.
        mkdir -p /src/dist
        out=$(ls -1 /src/target/release/bundle/appimage/*.AppImage | head -n1)
        for dst in "/src/dist/$(basename "$out")" /src/dist/grepfocus.AppImage; do
            cp "$out" "$dst.tmp" && mv -f "$dst.tmp" "$dst"
        done
        echo "built: $(basename "$out")"
    '

echo
echo "==> Built:"
ls -la dist/*.AppImage
echo
echo "==> Verify (extract + list): run"
echo "    ./dist/grepfocus.AppImage --appimage-extract >/dev/null && ls squashfs-root"
